### ISSUE TITLE
Clarify Complex Coverage example? 

### ISSUE THREAD

**Issue by elidoran** [diku-kmc/kleenexlang#17]
In [compile regular expressions into fast, streaming parsers](http://www.diku.dk/kmc/documents/GHR14-0-paper.pdf) section "8 Example" in the "complex coverage" example:

> Any expression of the form `x1zy1 +x2zy2 +x3z(y1 +y2)`...
Choose `x1 = x2 = (aa)*, x3 = a*, y1 = a, and y2 = b`. Figure 3 shows the expression
   `(aa)*za + aa*zb + a*za + b = (aa)*(za + zb) + a*z(a + b)` .

It says both x1 and x2 equal `(aa)*` but the `x2` is written without the parenthesis which changes it from the `(aa)*`, which means "any multiple of 2 counts of a, including zero", to `aa*` which means "at least one a" (or "one or more count of a"). 

Then, the right side combines the first two parts by factoring out the `(aa)*` which is only possible if both were written as `(aa)*` on the left.

So, it seems like there's either a typo or oversight because 1. it's written as `x1 = x2 = (aa)*`; and, 2. it's factored out as a part common to both. 

Also, the right side could be simplified further to `((aa)* + a*)z(a + b)` because `(aa)*(za + zb)` can factor out the `z` to become `(aa)*z(a + b)`, which is common to the other part. That shows it simplified and the third isn't subsumed by the first two. 

So, if there's a reason the x2 value was written differently and then factored out as if it was equal to x1, then please, someone explain it to me. :)  

And, why wasn't it all simplified down?

**Comment by ulrikrasmussen** [comment]
Dear Eli,

Thank you for the interest in our paper, and apologies for not answering earlier.

After reading this section again, I can confirm that there is indeed a typo in the example; the parentheses are missing in `aa*`.

Regarding the seemingly arbitrary choice of where to simplify and where not to, I can confirm that the choices are indeed arbitrary, and were made to keep the size of the example small enough while still exhibiting the complex coverage behavior. The simplification `ef + eg = e(f + g)` is actually dubious and is not sound in general with regards to the greedy leftmost matching semantics because it can change what local choices are made in `e` (although in this particular example, I think the refactoring is safe). For example, consider `e = aa + a`; `f = ax`; `g = x`. Then the LHS becomes `(aa + a)ax + (aa + a)x` and the RHS becomes `(aa + a)(ax + x)`. Consider the input string `aax` which is parsed differently by LHS and RHS with greedy leftmost disambiguation. LHS yields `inl (inr a, (a, x))` and the RHS yields `(inl aa, inr x)`: The local choices of all sums (`+`) are effectively flipped.

The example section has unfortunately been condensed too much for space reasons, and it therefore fails to explain that the method used to derive the example is an informal one that mainly serves to provide some intuition for the reader rather than being a general framework for constructing automata with complex coverage. Apologies for the confusion.

I hope the explanation helped, otherwise feel free to ask again :).

**Comment by elidoran** [comment]
I thank you for replying and explaining.  I see what you mean.
